### ISSUE TITLE
Create resources for more versions

### ISSUE THREAD

**Issue by slsevilla** [CCBR/RENEE#1]
- [ ] hg19 support
- [x] hg38 ... v30 through v36
- [x] mm10 ... newer than M21

prereq: [GTF at STAR command](https://github.com/CCBR/RNA-seek/issues/71)

**Comment by skchronicles** [comment]
Hey @slsevilla,

I am not sure if this is useful, but if you are working on Biowulf, I have also created some reference files for human and mouse here:

```
/data/OpenOmics/references/rna-seek/
```

Best Regards,
@skchronicles

**Comment by kopardev** [comment]
['hg38_30', 'hg38_34', 'hg38_38', 'hg38_41', 'mm10_M21', 'mm10_M23', 'mm10_M25'] support has been added to Biowulf and FRCE

**Comment by kopardev** [comment]
Also, #11
