### ISSUE TITLE
Renee build: qualimapinfo errors

### ISSUE THREAD

**Issue by slsevilla** [CCBR/RENEE#106]
I'm attempting to create a reference for T2T (HS1). Ran into two issues:

## Problem 1
Running `renee build` and had the rule `qualimapinfo` fail. The `.err`. and `.out` log were unhelpful. The script produces an error file but this being passed to `qualimap_error.log` which is not saved.
## Solution 1
The output should be to `.err` and not to a separate file

## Problem 2
Running this process:
```
python3 \
        data/Boufraqech_group/analysis/renee_build_240125/hs1_t2t/workflow/scripts/builder/generate_qualimap_ref.py \
        -g /data/Boufraqech_group/analysis/renee_build_240125/hs1_t2t/genes.gtf \
        -f /data/Boufraqech_group/analysis/renee_build_240125/hs1_t2t/hs1.fa \
        -o qualimap_info.txt \
        --ignore-strange-chrom 2> qualimap_error.log
``` 

Getting this error:
```
...
  File "/usr/local/Anaconda/envs/py3.10/lib/python3.10/site-packages/HTSeq/features.py", line 140, in __iter__
    (attr, name) = self.parse_GFF_attribute_string(
  File "/usr/local/Anaconda/envs/py3.10/lib/python3.10/site-packages/HTSeq/features.py", line 194, in parse_GFF_attribute_string
    raise ValueError(
ValueError: The attribute string seems to contain mismatched quotes.
```

## Solution 2
I figure out that this is because of single quotes in my GTF file
```
...addition of 3' A residues to the mRNA...
```
Still getting an error though - need to troubleshoot further.

**Comment by kopardev** [comment]
@slsevilla use [pyGTF](https://github.com/chengcz/pyGTF) to rewrite the GTF without unwanted "keys" from the last column for eg. "Note"

**Comment by kelly-sovacool** [comment]
solution was to rewrite the GTF without single quotes
