### ISSUE TITLE
Add HS1/T2T as genome reference

### ISSUE THREAD

**Issue by slsevilla** [CCBR/RENEE#109]
## Feature Request
Add HS1/T2T as a reference genome
- [ ] add to biowulf
- [ ] add to frce

**Comment by kopardev** [comment]
Does hs1's latest annotation have more genes (novel or new paralogs) than hg38's latest annotation?

@slsevilla Did you do a TechDev on this? Basically: Take human RNAseq data and:
- run with hg38 + latest annotation
- run with hs1 + its annotation
- do we get more read mappings with hs1?
- are these new mapping to genic regions?
- as hs1 has more "low-sequence-complexity" regions than hg38, 
  - does it take longer to align to hs1?
  - would this require changes to the alignment parameters?
- are gene-level raw counts changing significantly?

Has any PI requested hs1 specifically??

**Comment by slsevilla** [comment]
The PI who originally requested this now wants hg38. Moving this to the backburner.

**Comment by kopardev** [comment]
No longer requested.
