### ISSUE TITLE
Add QC check if no reads are left after `cutadapt`

### ISSUE THREAD

**Issue by slsevilla** [CCBR/RENEE#118]
## Problem
Recently had a project that had no reads left after trimming. The sample did not fail and continued downstream making it difficult to pinpoint where the sample had truly failed

## Solution
After cutadapt add a check to ensure there are suitable number of reads to move on in the pipeline.

**Comment by kelly-sovacool** [comment]
this can happen if a file contains only adapters -- make a unit test with adapters

**Comment by kelly-sovacool** [comment]
add code to cutadapt rule. if the file is empty, throw an error

**Comment by kelly-sovacool** [comment]
capture output from cutadapt summary

```
=== Summary ===

Total read pairs processed:              4,857
  Read 1 with adapter:                     555 (11.4%)
  Read 2 with adapter:                     604 (12.4%)
Pairs that were too short:                 604 (12.4%)
Pairs written (passing filters):         4,253 (87.6%)
```
