### ISSUE TITLE
add support for v45 reference from gencode

### ISSUE THREAD

**Issue by kopardev** [CCBR/RENEE#126]
- request from Parthav
- need to match SF ... they supporting v45 since 5/5/24

**Comment by kopardev** [comment]
@kelly-sovacool this is high priority. generate files on biowulf. move the reference files over to FRCE as well.

**Comment by kopardev** [comment]
fix #127

**Comment by kelly-sovacool** [comment]
hey @kopardev, #127 needs to be merged before I would consider this completed
