### ISSUE TITLE
set default human genome+annotation combo to match GDC

### ISSUE THREAD

**Issue by kopardev** [CCBR/RENEE#128]
Match GDC
- hg38
- v36
[ref](https://gdc.cancer.gov/about-data/gdc-data-processing/gdc-reference-files)

**Comment by kopardev** [comment]
First do #129

**Comment by kelly-sovacool** [comment]
@kopardev the `--genome` flag is a required argument and has no default. Can you explain what you mean by "change default human genome"?

https://github.com/CCBR/RENEE/blob/49696604d015652e019fed0ae82f9d52280fdd92/src/renee/__main__.py#L1859-L1864

**Comment by kelly-sovacool** [comment]
set hg38_36 as default, be explicit in the docs
