### ISSUE TITLE
Change human reference fasta 

### ISSUE THREAD

**Issue by kopardev** [CCBR/RENEE#129]
Match [GDC](https://gdc.cancer.gov/about-data/gdc-data-processing/gdc-reference-files)
- include decoys
- include viruses

Will need to 
- [x] recreate reference files for all human (h38/hg19) genomes + annotations combos on BIOWULF
- [x] move "new" reference files over to FRCE
- [ ] share "new" reference files with SF

**Comment by kelly-sovacool** [comment]
is XAVIER's fasta file the same as the GDC aggregated fasta file?

**Comment by kelly-sovacool** [comment]
files will be initially created here: `/data/CCBR_Pipeliner/db/PipeDB/GDC_refs`

@kopardev what's the best way to share these files with SF?

**Comment by kelly-sovacool** [comment]
see scripts here for how these were built: https://github.com/CCBR/build-renee-refs
