### ISSUE TITLE
docs: FAQ on searching for failed jobs in log files

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/RENEE#147]
e.g. grepping for fail/completed etc. in `snakemake.log.jobby.short`

**Comment by samarth8392** [comment]
@kelly-sovacool take a look at ESCAPE [FAQs](https://stunning-waffle-p8p5m5q.pages.github.io/user-guide/troubleshooting/) and see if something similar for RENEE would work?

**Comment by kelly-sovacool** [comment]
> @kelly-sovacool take a look at ESCAPE [FAQs](https://stunning-waffle-p8p5m5q.pages.github.io/user-guide/troubleshooting/) and see if something similar for RENEE would work?

I think that's a good start, and we'll also want renee-specific info like referencing the jobby output files and how to interpret them
