### ISSUE TITLE
Make rna-seek use GTF at alignment command

### ISSUE THREAD

**Issue by slsevilla** [CCBR/RENEE#2]
Currently 5 different readlength indexes need to be made ahead of time ... this is totally unnecessary!
Create single index for each genome ... eg. 1 for hg38 and 1 for mm10 and keep GTF files available to be added at command line.

**Comment by skchronicles** [comment]
Hey @slsevilla,

We are already doing this at the current moment. If you have any issues, can you please open them in the [main repository here](https://github.com/skchronicles/RNA-seek) so I am aware of any problems and can address them? I use this pipeline daily so if there is an issue, I would like to know.

Best Regards,
Skyler Kuhn
