### ISSUE TITLE
No Genomic BAM

### ISSUE THREAD

**Issue by kopardev** [CCBR/RENEE#30]
Files are deleted:

https://github.com/CCBR/RENEE/blob/10ace58d79f42a9b85e58500e117cba7db271aa2/workflow/rules/paired-end.smk#L381

https://github.com/CCBR/RENEE/blob/10ace58d79f42a9b85e58500e117cba7db271aa2/workflow/rules/single-end.smk#L432

They should be kept.
Also ensure that the correct BAM's are used to generate the bigwigs.

**Comment by kelly-sovacool** [comment]
add a flag to optionally keep this file -- useful for sashimi plots, but large

**Comment by kelly-sovacool** [comment]
@kopardev question: should we actually keep the sorted bam file?

https://github.com/CCBR/RENEE/blob/4d42da400106756644e9ba5345271185214fa77c/workflow/rules/paired-end.smk#L294

**Comment by kopardev** [comment]
~@kelly-sovacool ... you are right ... just remove the `temp` from line 294 and we should be fine. ... no need to keep `.Aligned.out.bam` as it is the unsorted version of the same file.~

**Comment by kopardev** [comment]
Actually `.star_rg_added.sorted.dmark.bam` is the **GENOMIC BAM**... I dont know what I was under when I made this issue 🚬 🍹

**Comment by kelly-sovacool** [comment]
> Actually `.star_rg_added.sorted.dmark.bam` is the **GENOMIC BAM**... I dont know what I was under when I made this issue 🚬 🍹

IIRC an analyst (Kate?) raised this issue originally. Perhaps the docs aren't clear enough? What do you think?

https://github.com/CCBR/RENEE/blob/4d42da400106756644e9ba5345271185214fa77c/docs/RNA-seq/output.md?plain=1#L46
