### ISSUE TITLE
`config.json` should only be generated if it doesnt exist

### ISSUE THREAD

**Issue by kopardev** [CCBR/RENEE#34]
Currently `config.json` is generated everytime `renee` is run:
- initialization
- dryrun
- run, etc.
It should be only generated at initialization, which may then be edited. Hence, it should NOT be regenerated and possibly overwritten!

**Comment by kelly-sovacool** [comment]
We had this same problem in XAVIER. Adding an if/else to only run `setup()` if `runmode == 'init'` should do the trick.
https://github.com/CCBR/XAVIER/issues/29

**Comment by kopardev** [comment]
Fixed in #39
