### ISSUE TITLE
doc: create documentation for GUI

### ISSUE THREAD

**Issue by kopardev** [CCBR/RENEE#38]
- "How to use the gui" docs are required!
- where are the test data files
- where are the expected outputs?

XAVIER gui docs for inspiration: https://ccbr.github.io/XAVIER/usage/gui/

**Comment by kelly-sovacool** [comment]
@samarth8392 do you know if the GUI documentation for RENEE already exists and maybe we just didn't realize it?

**Comment by samarth8392** [comment]
I only worked on XAVIER GUI documentation but I can add similar documentation to RENEE as well. Just assign it to me and I will get it done.

**Comment by samarth8392** [comment]
@kopardev @kelly-sovacool I don't have the permission to create branches on RENEE and I don't see the "settings" tab on RENEE repo. Can one or either of you change the permissions so that I may be able to work on this issue?

**Comment by kelly-sovacool** [comment]
@samarth8392 I just added you!
