### ISSUE TITLE
Shared resource path outside git repo

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/RENEE#54]
RENEE requires a shared resource dir which is outside the git repo.

It's set here:
https://github.com/CCBR/RENEE/blob/22a558115a7edd0893023cbb9e3bc612e978947b/renee#L46-L48

This makes RENEE only able to run when there's also a resources dir in the same parent dir as the repo, i.e. how it's set up on biowulf in `/data/CCBR_Pipeliner/Pipelines`, which makes it less portable and more difficult to test.

**Comment by kelly-sovacool** [comment]
If shared resources outside the repo are required (e.g. genome references), they should not be hardcoded but should be flexibly set by a config param or something similar so they can be overriden.

**Comment by kelly-sovacool** [comment]
This code was added at https://github.com/CCBR/RENEE/commit/20fe2b26b9934fe7f4ea2d138d7256fdf18421b8 as a hotfix. Shouldn't be needed because the files are redundant with what's in the git repo.

**Comment by slsevilla** [comment]
fix: #66
