### ISSUE TITLE
set default --tmp-dir depending on HPC platform

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/RENEE#79]
Currently, the default `--tmp-dir` is `/lscratch/$SLURM_JOBID`, which only works on biowulf. FRCE users are expected to set this to `/scratch/cluster_scratch/$USER/`. We could instead have the default detect the HPC platform and set it to these defaults accordingly, and users on other platforms can still override it.

**Comment by kelly-sovacool** [comment]
Until we resolve this issue, RENEE doesn't work on frce unless you set `--tmp-dir`

**Comment by slsevilla** [comment]
My `frce` run did not error due to tmp dir issues

**Comment by kelly-sovacool** [comment]
@slsevilla looks like you manually closed this as completed instead of merging the PR https://github.com/CCBR/RENEE/pull/98

**Comment by slsevilla** [comment]
Oops! You're right. Bad habit!

**Comment by kelly-sovacool** [comment]
Thanks Sam! Doing it this way helps track which PRs fixed which issues.
