### ISSUE TITLE
error in star2p: could not create output file

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/RENEE#81]
@kopardev could this be related to the rNA_report error where the output also couldn't be written?

Command:

```sh
module load ccbrpipeliner
renee run \
  --input /data/CCBR_Pipeliner/Pipelines/RENEE/develop/.tests/*.R1.fastq.gz \
  --output /data/sovacoolkl/renee_test_v2.5.10 \
  --genome hg38_30 \
  --mode slurm \
  --sif-cache /data/CCBR_Pipeliner/SIFS
```

contents of `/data/sovacoolkl/renee_test_v2.5.10/logfiles/slurmfiles/16423847.16425270.star2p.name=WT_S1.err`:

```
Activating singularity image /data/CCBR_Pipeliner/SIFS/ccbr_arriba_2.0.0_v0.0.1.sif

BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file /lscratch/16425270/tmp.HxPt2YcFFl/STARtmp_WT_S1//BAMsort/19/47
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.

Jan 05 12:21:40 ...... FATAL ERROR, exiting
```

**Comment by kopardev** [comment]
Possibly:
- filesystem latency on `/lscratch` ... highly unlikely being a solid-state device
- mounted `/lscratch` is a shared with other job (by some other user) which is generating too many small files ... going past the inode limit.

**Comment by kelly-sovacool** [comment]
on a second run this completed successfully; I think it was a one-off error related to ulimit
