### ISSUE TITLE
Support Arriba for other genomes

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/RENEE#90]
It only supports hg38 and mm10 by default. We may need to reach out to the Arriba maintainer for help creating these fusion files for other genome annotations.

https://github.com/CCBR/RENEE/blob/5fb4d14e8ea57e42dd32e18ae9cee0db7616d58c/config/genomes/biowulf/hg38_30.json#L20-L22

**Comment by kopardev** [comment]
Linked to #12

**Comment by kelly-sovacool** [comment]
there is likely an if statement checking for the genome and only running arriba on hg38 -- will need to remove this

**Comment by kelly-sovacool** [comment]
hg19 blacklist and fusion files are included in arriba: https://arriba.readthedocs.io/en/latest/input-files/#blacklist

first let's download on biowulf, later will put them in our s3 bucket

**Comment by kelly-sovacool** [comment]
> there is likely an if statement checking for the genome and only running arriba on hg38 -- will need to remove this

this appears to be implemented correctly https://github.com/CCBR/RENEE/blob/ee1a9e444b482460c669d21b734e3eec4ad6cc3c/workflow/rules/paired-end.smk#L612

**Comment by kelly-sovacool** [comment]
closing in favor of #12. All that is needed is to upload the mm39 resources to S3 and update the `jsonmaker` rule to support mm39 https://github.com/CCBR/RENEE/blob/6af726a214afd578a769d42e2755eb1a43806f50/workflow/rules/build.smk#L657
